### ISSUE TITLE
Problems met when Installing grid-based operators

### ISSUE THREAD

**Issue by sea-comet** [dvlab-research/BlockNeRFPytorch#109]
Hi, 
I encountered the error below when installing grid-based operators, any ideas how to solve it? Thanks! 
`
(large-scale-nerf) shuyuan@shuyuan-3090:~/LargeScaleNeRFPytorch/FourierGrid/cuda$ python setup.py install
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
running install
/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing adam_upd_cuda.egg-info/PKG-INFO
writing dependency_links to adam_upd_cuda.egg-info/dependency_links.txt
writing top-level names to adam_upd_cuda.egg-info/top_level.txt
reading manifest file 'adam_upd_cuda.egg-info/SOURCES.txt'
writing manifest file 'adam_upd_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "/home/shuyuan/LargeScaleNeRFPytorch/FourierGrid/cuda/setup.py", line 15, in <module>
    setup_sources(name='adam_upd_cuda', sources=['adam_upd.cpp', 'adam_upd_kernel.cu'])
  File "/home/shuyuan/LargeScaleNeRFPytorch/FourierGrid/cuda/setup.py", line 10, in setup_sources
    setup(name=name,
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 383, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/shuyuan/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
`

**Comment by sea-comet** [comment]
My cuda envirment is 11.7, and I followed every single command you listed. Don't know why this error happened. Please help me with it. Thanks!

**Comment by sjtuytc** [comment]
大概是版本问题，pytorch版本更新一下，老板本parse不了版本号

**Comment by sjtuytc** [comment]
pytorch version has a problem. So It's version number cannot be parsed.

**Comment by sjtuytc** [comment]
What's your torch.version.cuda? Print it out.

**Comment by sea-comet** [comment]
谢谢！问题解决了，是torch.cuda不工作，重装了一遍，把安装torch的步骤提到安装其它包之前就好了。
