### ISSUE TITLE
Problems occuars when installing grid-based operators

### ISSUE THREAD

**Issue by Bingzhi-Yuan-1987** [dvlab-research/BlockNeRFPytorch#113]
Hi, I encountered an issue when I'm trying to install the grid-based operators, is there anyone knows how to solve it? Any help will be appreciated.
`installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py:398: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'adam_upd_cuda' extension
Traceback (most recent call last):
  File "/home/yuanbingzhi/UnboundedNeRFPytorch/FourierGrid/cuda/setup.py", line 15, in <module>
    setup_sources(name='adam_upd_cuda', sources=['adam_upd.cpp', 'adam_upd_kernel.cu'])
  File "/home/yuanbingzhi/UnboundedNeRFPytorch/FourierGrid/cuda/setup.py", line 10, in setup_sources
    setup(name=name,
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
    objects = self.compiler.compile(
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 649, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/yuanbingzhi/anaconda3/envs/large-scale-nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1773, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range`

**Comment by Bingzhi-Yuan-1987** [comment]
I'm using pytorch with cuda 11.8 on WSL. the gcc version is 11.3 and the nvcc is 11.8.89.
I followed the commands that are listed. Please help me with this issue. Thx.

**Comment by sjtuytc** [comment]
This is a rare problem but I remembered that I have met it once before. It seems to be a problem of CUDA. Can you try to Google it？

**Comment by sjtuytc** [comment]
Another suggestion is that you can find out which line is in trouble and I can help you then.

**Comment by Bingzhi-Yuan-1987** [comment]
> _get_cuda_arch_flags arch_list[-1] += '+PTX' IndexError: list index out of range
Thank you for your hint. It is a CUDA issue and it is solve by using command `TORCH_CUDA_ARCH_LIST="5.2 6.0 6.1 7.0 7.5 8.0 8.6+PTX" python setup.py install`  instead of `python setup.py install`

**Comment by sjtuytc** [comment]
Resolved.
