### ISSUE TITLE
LIFF数据集运行mip-nerf 360

### ISSUE THREAD

**Issue by cnu-Dawn** [dvlab-research/BlockNeRFPytorch#122]
Loading images from ./data/360_v2/garden/images_8

Mismatch between imgs 363 and poses 726 !!!!
Traceback (most recent call last):
  File "run_FourierGrid.py", line 97, in <module>
    data_dict, args = load_everything(args=args, cfg=cfg)
  File "/root/autodl-tmp/nerf/LargeScaleNeRFPytorch-main/FourierGrid/load_everything.py", line 24, in load_everything
    data_dict = load_common_data(cfg.data)
  File "/root/autodl-tmp/nerf/LargeScaleNeRFPytorch-main/FourierGrid/common_data_loaders/load_common_data.py", line 19, in load_common_data
    images, depths, poses, bds, render_poses, i_test = load_llff_data(
  File "/root/autodl-tmp/nerf/LargeScaleNeRFPytorch-main/FourierGrid/common_data_loaders/load_llff.py", line 303, in load_llff_data
    poses, bds, imgs, *depths = _load_data(basedir, factor=factor, width=width, height=height,
  File "/root/autodl-tmp/nerf/LargeScaleNeRFPytorch-main/FourierGrid/common_data_loaders/load_llff.py", line 132, in _load_data
    assert len(names) == poses.shape[-1]
AssertionError
我在用自己的数据集运行mip-nerf 360时出现了如下错误，请问该如何解决

**Comment by sjtuytc** [comment]
图片少了或者不存在，另外你自己的数据集为什么名字叫garden
