### ISSUE TITLE
No such file or directory: coordinates.pt

### ISSUE THREAD

**Issue by guanjunwu** [dvlab-research/BlockNeRFPytorch#51]
Hello ,I'm a student from HUST . Recently I'm running Mega-NeRF on Waymo Dataset and trying to do some experiments. Knowing that this project have finished the task ,so I try to running the program on this code hub. Unfortunately ,the script callback a error explained that `No such file or directory`.
I think I follow the correct steps ,firstly I download the Waymo dataset ,and run the script `get_one_block_meta_and_visualize.py` and `split_block.py`.I found the file coordinate.pt do not exists exactly .I'm confused , I don't know what step is wrong. Can you help me?
```python
Traceback (most recent call last):
  File "create_cluster_masks.py", line 214, in <module>
    main(_get_mask_opts())
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "create_cluster_masks.py", line 57, in main
    coordinate_info = torch.load(dataset_path / 'coordinates.pt', map_location='cpu')
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '~/data/data/pytorch_waymo_dataset/coordinates.pt'
```

**Comment by guanjunwu** [comment]
sorry
