### ISSUE TITLE
运行waymo数据集格式转换脚本fetch_data_from_tf_record.py 出错

### ISSUE THREAD

**Issue by Bin-ze** [dvlab-research/BlockNeRFPytorch#99]
我使用fetch_data_from_tf_record.py尝试将tf格式转换为pytorch，但是出现以下错误：

    '''
    Traceback (most recent call last):
      File "/home/work_code/LargeScaleNeRFPytorch/data_preprocess/fetch_data_from_tf_record.py", line 180, in <module>
        train_index, val_index = handle_one_record(tfrecord, train_index, val_index)
      File "/home/work_code/LargeScaleNeRFPytorch/data_preprocess/fetch_data_from_tf_record.py", line 98, in handle_one_record
        for batch in dataset_map:
      File "/home/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 787, in __next__
        return self._next_internal()
      File "/home/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 770, in _next_internal
        ret = gen_dataset_ops.iterator_get_next(
      File "/home/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3017, in iterator_get_next
        _ops.raise_from_not_ok_status(e, name)
      File "/home/miniconda3/envs/large-scale-nerf/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
        raise core._status_to_exception(e) from None  # pylint: disable=protected-access
    tensorflow.python.framework.errors_impl.DataLossError: {{function_node __wrapped__IteratorGetNext_output_types_9_device_/job:localhost/replica:0/task:0/device:CPU:0}} inflate() failed with error -3: incorrect header check [Op:IteratorGetNext]
    '''

请问我该如何让解决？

**Comment by sjtuytc** [comment]
这个问题我没有遇到过，看起来是tensorflow的版本问题，应该跟本仓库无关。可以考虑谷歌一下。
